VOCAB.BUILDING = [
    "gate",
    "church of <FAITH_GRAMMAR>",
    "<SUBJECT|MINERAL> market",
    "house",
    "home of a <TRAIT|> <PROFESSION>",
    "home of a <PROFESSION>",
    "house of <PROFESSION> killer",
    "<PROFESSION|SUBJECT|ANIMAL|> tower",
    "port",
    "<ANIMAL|SUBJECT> shop",
    "workshop",    
    "station",   
    "shrine",
    "fountain",
    "university of <ABSTRACT|MAGIC>",
    "<PERSON>'s laboratory",
    "<MINERAL> mine",
    "factory",
    "fortress",
    "monument",
    "<ANIMAL|> farm",
    "<FOOD|SUBJECT|> storage",
    "guild house", 
    "crypt",
    "wreck",
    "temple",
    "cathedral",    
    "castle",    
    "statue of a <SUBJECT|PERSON>",
    "lighthouse",
    "pub",
    "hotel",
    "library",
    "brothel", 
    "distillery",   
    "interdimensional portal", 
];