VOCAB.PROFESSION = [
    "mage",
    "hunter",
    "alchemyst",
    "knight",
    "priest",
    "blacksmith",
    "merchant",
    "rebel",
    "thief",
    "murderer",
    "courtesan",
    "fisherman",
    "<ABSTRACT> teacher",
    "rogue",
    "archer",
    "guard",
    "leader",
    "man",
    "woman",
    "hero",
    "villain",
    "trader",
    "warlock",
    "bard",
    "keymaster",
];