VOCAB.CREATURE = [
    "basilisk",
    "kraken",
    "leviathan",
    "manticore",
    "dragon",
    "gargoyle",
    "pegasus",
    "unicorn",
    "wraith",
    "phoenix",
    "spirit",

];
//     "angel","archer","archon",
//     "army","assassin","assembly-worker","avatar",
//     "badger",,"bear","beast","beeble","berserker",
//     "bird","blinkmoth","bringer","brushwagg","camarid","camel","caribou","carrier",
//     "cat","centaur","cephalid","chimera","citizen","cleric","cockatrice","construct","coward",
//     "crab","crocodile","dauthi","demigod","demon","deserter","devil","dinosaur",
//     "djinn","dog","dragon","drake","dreadnought","drone","druid","dryad","dwarf","efreet",
//     "egg","elder","eldrazi","elemental","elf","elk","eye","faerie","ferret","fish",
//     "flagbearer","fungus",,"germ","giant","gnome","goat","goblin","god",
//     "golem","gorgon","graveborn","gremlin","griffin","hag","harpy","hellion","hippo","hippogriff",
//     "homarid","homunculus","horror","horse","human","hydra","","illusion","imp",
//     "incarnation","knight",
//     ,,"mercenary","","metathran","minion","minotaur","mole","monger",
//     "mongoose",,,,"","","mystic",,"",
//     ,"nightmare","nightstalker","ninja","noble","noggle","nomad","nymph","octopus",
//     "ogre","ooze","orb","","","oyster","","peasant",
//     "pegasus","pest","plant",
//     ,"rebel","reflection",
//     "rogue",
//     "scion","scorpion","scout","serf","servo","shade",
//     "shapeshifter","shark","slith","sliver",
//     "snake","soldier","soltari","spawn","specter",,"sphinx",
//     "spike","spirit","splinter","sponge",
//     ,"treefolk",
//    ,
//     ,"weird","",
//     ,"wurm",


VOCAB.HUMANOID = [
    "ape",
    "barbarian",
    "cyclops", "centaur", "celestial being",
    "demon", "dryad", "dwarf",
    "elf",
    "goblin", "giant", "[ELEMENT] giant",
    "harpy",
    "imp",
    "kobold",
    "lizardman", "lich",
    "mermaid", "minotaur", "mummy",
    "monk", "monkey", "[ANIMAL]-man",
    "mutant",
    "naga", "[ELEMENT] nymph",
    "ninja",
    "orc", "ogre",
    "pirate",
    "siren","skeleton", "survivor", "satyr", "spellshaper", "shaman","succubus", "shapeshifter",
    "troll",
    "vampire", "vampire queen",
    "werewolf","warlock","warrior", "wizard",
    "yetti","zombie"

];

VOCAB.FISH = [
    "eel",
    "catfish",
    "shark",
    "piranha",
    "tuna",
    "salmon"
]

VOCAB.COLOR = [
  "black",
  "white",
  "green",
  "red",
  "yellow",
  "blue",
  "orange",
  "pink",
  "violet",
  "purple",
  "brown",
];

VOCAB.ANIMAL = [
    "[FISH]",
    "antelope", "ape",
    "bird",
    "bat", "beetle",
    "boar","bear",
    "leech",
    "chicken", "cow", "cat",
    "dog",
    "elephant", "eagle",
    "fish",
    "fox","frog",
    "goat",
    "horse",
    "hyena",
    "jackal","jellyfish",
    "lizard", "lamb",
    "mouse", "monkey",
    "ox", "otter", "owl", "octopus",
    "pig", "pony",
    "rat", "rabbit", "rhino",
    "sheep", "scorpion", "squid","squirrel","starfish", "slug", "serpent",
    "snake", "spider", "salamander", "stag",
    "turtle",
    "wasp",
    "wolf", "whale", "winter stag",
    "wolverine","wombat","worm",
];