VOCAB.CREATURE = [
    "basilisk",
    "kraken",
    "leviathan",
    "manticore",
    "dragon",
    "gargoyle",
    "unicorn",
    "wraith",
    "phoenix",

];
//     "angel","archer","archon",
//     "army","assassin","assembly-worker","avatar",
//     "badger",,"bear","beast","beeble","berserker",
//     "bird","blinkmoth","bringer","brushwagg","camarid","camel","caribou","carrier",
//     "cat","centaur","cephalid","chimera","citizen","cleric","cockatrice","construct","coward",
//     "crab","crocodile","dauthi","demigod","demon","deserter","devil","dinosaur",
//     "djinn","dog","dragon","drake","dreadnought","drone","druid","dryad","dwarf","efreet",
//     "egg","elder","eldrazi","elemental","elf","elk","eye","faerie","ferret","fish",
//     "flagbearer","fungus",,"germ","giant","gnome","goat","goblin","god",
//     "golem","gorgon","graveborn","gremlin","griffin","hag","harpy","hellion","hippo","hippogriff",
//     "homarid","homunculus","horror","horse","human","hydra","","illusion","imp",
//     "incarnation","knight",
//     ,,"mercenary","","metathran","minion","minotaur","mole","monger",
//     "mongoose",,,,"","","mystic",,"",
//     ,"nightmare","nightstalker","ninja","noble","noggle","nomad","nymph","octopus",
//     "ogre","ooze","orb","","","oyster","","peasant",
//     "pegasus","pest","plant",
//     ,"rebel","reflection",
//     "rogue",
//     "scion","scorpion","scout","serf","servo","shade",
//     "shapeshifter","shark","slith","sliver",
//     "snake","soldier","soltari","spawn","specter",,"sphinx",
//     "spike","spirit","splinter","sponge",
//     ,"treefolk",
//    ,
//     ,"weird","",
//     ,"wurm",


VOCAB.HUMANOID = [
    "ape",
    "barbarian",
    "cyclops",
    "demon",
    "elephant",
    "goblin", "giant",
    "imp",
    "kobold",
    "lizardman",
    "mermaid",
    "monk",
    "monkey",
    "mutant",
    "naga",
    "ninja",
    "orc", "ogre",
    "pirate",
    "siren","skeleton", "survivor", "satyr", "spellshaper", "shaman",
    "troll",
    "vampire",
    "vampire queen",
    "werewolf","warlock","warrior", "wizard",
    "yetti","zombie"
];

VOCAB.ANIMAL = [
    "antelope", "ape",
    "bird",
    "bat",
    "boar","bear",
    "leech",
    "chicken",
    "dog",    
    "fish",
    "fox","frog",
    "horse",
    "hyena",
    "insect",
    "jackal","jellyfish",
    "lizard",    
    "mouse", "monkey",
    "ox", "otter",
    "pig",
    "rat", "rabbit", "rhino",
    "sheep", "scorpion", "squid","squirrel","starfish", "slug", "serpent",
    "snake", "spider", "salamander",
    "turtle",
    "wolf", "whale",
    "wolverine","wombat","worm",
];