var VOCAB = {
 
BUILDING_GRAMMAR : [

    "<ADJ:SIZE:_M|> <ADJ:CONDITION:_M> <BUILDING_M>",
    "<ADJ:SIZE:_S|> <ADJ:CONDITION:_S> <BUILDING_S>",
    "<ADJ:SIZE:_F|> <ADJ:CONDITION:_F> <BUILDING_F>",
    // "<SIZE|> <CONDITION> <MATERIAL> <BUILDING>",
    // "<SIZE|> <CONDITION> <AREA>",
    // "<CONDITION> <BUILDING> <BUILDING_STATE_GRAMMAR|>",
],

BUILDING_STATE_GRAMMAR : [
    "looking <TRAIT>",
    "swarming with <ANIMALS>",
],

FAITH_GRAMMAR: [
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> bůh <GOD_ASPECT_2>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> pán <GOD_ASPECT_2>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> strážce <BIOME_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_F|ADJ:TRAIT:_F> <ADJ:RACE:_F|> strážkyně <BIOME_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> ochránce <ANIMAL_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_F|ADJ:TRAIT:_F> <ADJ:RACE:_F|> bohyně <GOD_ASPECT_2>", 
],

CHARACTER_GRAMMAR: [
    "<NAMES_M|NAMES_M2>, <ADJ:TRAIT:_M|> <ADJ:RACE:_M|> <PROFESSION_M> <CLOTHES_7|WEAPON_7|>",
    "<NAMES_F>, <ADJ:TRAIT:_F|> <ADJ:RACE:_F|> <PROFESSION_F> <CLOTHES_7|WEAPON_7|>",    
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|RACE|> <PROFESSION> <CLOTHES_GRAMMAR>, <WEAPON_GRAMMAR>",
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|> <RACE> <PROFESSION> <CLOTHES_GRAMMAR>",
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|> <PROFESSION|ANIMAL> killer",
],

MONSTER_GRAMMAR: [
    "<ADJ:TRAIT:_M> <ADJ:RACE:_M|> <ADJ:MATERIAL:_M> golem <CLOTHES_7|WEAPON_7|>",
    "<ADJ:TRAIT:_F> <ADJ:RACE:_F|> <ANIMAL_F> <FEATURE_7>",
    "<ADJ:TRAIT:_M> <ADJ:RACE:_M|> <ANIMAL_M> <FEATURE_7>"
    // "<TRAIT|CONDITION> <ELEMENT|MATERIAL|FOOD> golem that looks <TRAIT>"
],

CITY_NAME_GRAMMAR: [
    "<CITY_NAME_START><CITY_NAME_MID|><CITY_NAME_END>",    
    "<CITY_NAME_START><CITY_NAME_MID|><CITY_NAME_END>",    
    "<CITY_NAME_START><CITY_NAME_MID|><CITY_NAME_END>",
],

CITY_DESC_GRAMMAR: [
    ", <COMMUNITY> ve <BIOME_6_E>",
    ", <COMMUNITY> v <BIOME_6>",
    ", <COMMUNITY> u <BIOME_2_MN>",
    ", <COMMUNITY> <BIOME_ATYP>"
],

STORY_GRAMMAR: [        
    "<PROFESSION_M|PROFESSION_F> <VERB>",
    //"<PROFESSION_M> <VERBS:VERB_PAST:_M>",
    //"<PROFESSION_F> <VERBS:VERB_PAST:_F>"
],

MAIN_STORY_GRAMMAR: [        
    "<PROFESSION_M> <CHARACTER_STORY:_M>",
    "<PROFESSION_F> <CHARACTER_STORY:_F>",
    "<PROFESSION_S> <CHARACTER_STORY:_S>",
    "Před <BUILDING_M_7|BUILDING_S_7|BUILDING_F_7> byl nalezen <ADJ:TRAIT:_M> <ANIMAL_M|PROFESSION_M>",    
    "Před <BUILDING_M_7|BUILDING_S_7|BUILDING_F_7> byla nalezena <ADJ:TRAIT:_F> <ANIMAL_F|PROFESSION_F>"  
    //"<PROFESSION_M> <VERBS:VERB_PAST:_M>",
    //"<PROFESSION_F> <VERBS:VERB_PAST:_F>"
],

CHARACTER_STORY: [
    "je nezvěstn<$1$>, stopy vedou do <APPEARENCE_ML><$1$_2> <TARGETLOC$1$_2>.",
    "je nalezen<$1$> mrtv<$1$> u <TARGETLOC$1$_2>, kolem jsou stopy <ANIMAL_2_MN>."    
],

FLAVOR_STORY_GRAMMAR: [        
    "<PROFESSION_M|PROFESSION_F> <VERB>",
    //"<PROFESSION_M> <VERBS:VERB_PAST:_M>",
    //"<PROFESSION_F> <VERBS:VERB_PAST:_F>"
],

};