var VOCAB = {
 
BUILDING_GRAMMAR : [

    "<ADJ:SIZE:_M|> <ADJ:CONDITION:_M> <BUILDING_M>",
    "<ADJ:SIZE:_S|> <ADJ:CONDITION:_S> <BUILDING_S>",
    "<ADJ:SIZE:_F|> <ADJ:CONDITION:_F> <BUILDING_F>",
    // "<SIZE|> <CONDITION> <MATERIAL> <BUILDING>",
    // "<SIZE|> <CONDITION> <AREA>",
    // "<CONDITION> <BUILDING> <BUILDING_STATE_GRAMMAR|>",
],

BUILDING_STATE_GRAMMAR : [
    "looking <TRAIT>",
    "swarming with <ANIMALS>",
],

FAITH_GRAMMAR: [
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> bůh <ELEMENT_2>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> pán <ELEMENT_2>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> strážce <BIOME_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_F|ADJ:TRAIT:_F> <ADJ:RACE:_F|> strážkyně <BIOME_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_M|ADJ:TRAIT:_M> <ADJ:RACE:_M|> ochránce <ANIMAL_2_MN>", 
    "<GODNAME>, <ADJ:APPEARENCE_CHAR:_F|ADJ:TRAIT:_F> <ADJ:RACE:_F|> bohyně <ELEMENT_2>", 
],

CHARACTER_GRAMMAR: [
    "<NAMES_1|NAMES_2|NAMES_3>, <ADJ:TRAIT:_M|> <ADJ:RACE:_M|> <PROFESSION_M> <CLOTHES_7|WEAPON_7|>",
    "<NAMES_1|NAMES_2|NAMES_3>, <ADJ:TRAIT:_F|> <ADJ:RACE:_F|> <PROFESSION_F> <CLOTHES_7|WEAPON_7|>",    
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|RACE|> <PROFESSION> <CLOTHES_GRAMMAR>, <WEAPON_GRAMMAR>",
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|> <RACE> <PROFESSION> <CLOTHES_GRAMMAR>",
    // "<NAMES_1|NAMES_2|NAMES_3>, the <TRAIT|TRAIT|> <PROFESSION|ANIMAL> killer",
],

MONSTER_GRAMMAR: [
    "<ADJ:TRAIT:_M> <ADJ:RACE:_M|> <ADJ:MATERIAL:_M> golem <CLOTHES_7|WEAPON_7|>",
    "<ADJ:TRAIT:_F> <ADJ:RACE:_F|> bestie <FEATURE_7>"
    // "<TRAIT|CONDITION> <ELEMENT|MATERIAL|FOOD> golem that looks <TRAIT>"
],

CITY_NAMES_GRAMMAR: [
    "?"
//    "<CITY_NAME_PART>",
//    "<WORD> <CITY_NAME_PART|>",
//    "<WORD>-<CITY_NAME_PART>",
],

CITY_NAME_PART: [
    "?"
    // "<WORD><CITY_NAME_END>",  
    // "<CONSONANT><VOWEL><CITY_NAME_MID|><CITY_NAME_END> ",
    // "<WORD><CITY_NAME_END>",  
],

WORD: [
    "?"
    // "<CONSONANT><VOWEL>",
    // "<CITY_NAME_MID>",
    // "<CITY_NAME_MID><CITY_NAME_MID>",
    // "<CONSONANT><VOWEL><CITY_NAME_MID><CONSONANT><VOWEL>",
    // "<CONSONANT><VOWEL><CONSONANT><VOWEL>",
    // "<CONSONANT><VOWEL><CITY_NAME_PAIR>",
    // "<CONSONANT><VOWEL><CITY_NAME_PAIR><CITY_NAME_PAIR2>",
    // "<CONSONANT><VOWEL><CITY_NAME_PAIR><CITY_NAME_PAIR2><CONSONANT><VOWEL>",
    // "<CONSONANT><VOWEL><CONSONANT><VOWEL><CONSONANT><VOWEL>",
],

WEAPON_GRAMMAR: [    
    "?"
    // "holding <TOOL|WEAPON|BODY_PART>",
    // "armed with <CONDITION|> <MINERAL|> <WEAPON>",
    // "skillful with <CONDITION|> <WEAPON|INSTRUMENT>", 
],

STORY_GRAMMAR: [    
    "?"
    // "<PROFESSION> <VERB>",    
],

};