VOCAB.CLOTHES_6 = [
    "v masce",
    "v ceremoniální čelence",
    "v ornamentální čelence",
    "s brýlemi",
    "se [METAL_ML|GEM_ML][_F_7] korunou",
    "se [METAL_ML|GEM_ML][_F_7] korunou",
    "s archaickou helmou",
    "s [METAL_ML|GEM_ML][_M_7] náhrdelníkem",
    "s amuletem",
    "v klobouku", 
    "se zavázanýma očima",
    "s oholenou hlavou",
    "s dlouhými vlasy",
    "s dredy",
    "s copem",
    "v obvazech",
    "s infekcí",
    "v [COLOR][_F_MN_6] šatech"
];

VOCAB.ORIGIN = [
    "tribal",
];

VOCAB.FEATURE_7 = [
    "s křídly",
    "s démonickými křídly",
    "s hmyzími křídly",
    "s [LENGTH]ým ocasem",
    "s ostny na hřbetě",
    "s ostny na ocase",
    "s placatým ocasem",
    "s elektrickým ocasem",
    "s žahavým jazykem",
    "s žahavými výrůstky",
    "s širokou čelistí",
    "s dlouhým krkem",
    "s žihadlem",
    "s [LENGTH]ým čumákem",
    "s [LENGTH]ým rypákem",
    "se zakroucenými rohy",
    "s [LENGTH]ými tesáky",
    "s [LENGTH]ými zubami",
    "s [LENGTH]ými chapadly",
    "s šupinami",
    "s [COLOR]ými pruhy",
    "s [COLOR]ými skvrnami",
    "s [COLOR]ou skvrnou na těle",
    "s [COLOR]ou skvrnou na ocase",
    "s [COLOR]ou skvrnou na nohách",
    "s [COLOR]ou skvrnou na hlavě",
    "s [COLOR]ou čelistí",
    "s vnitřním zdrojem moci",
    "se svíticíma očima",
    "bez očí",
    "s [SIZE_ML]ýma očima",
    "s [LENGTH]ými nohami",
    "s [LENGTH]ými pařáty",
    "s [LENGTH]ými drápy",
    "s [LENGTH]ými kly",
    "se [NUMBER_7] očima",
    "s jedním okem",
    "se [NUMBER_7] hlavami",
    "se dvěma ocasy",
    "se šesti nohami",
    "se špičatým rohem",
    "se špičatýma ušima",
    "s dlouhýma ušima",
    "s krátkými uši",
    "s malou hlavou",
    "s výrůstky na bradě",
    "s chapadly na bradě",
    "s bodáky na bradě",
    "s chobotem",
    "s dlouhou hřívou",
    "s hustým kožichem",
    "s dlouhými tykadli",
    "se zkroucenými tykadli",
    "s krycím zbarvením",
    "se zbarvením listů",
    "se zbarvením kamení",
    "se zbarvením kůry",
    "s lalokem na hrdle",
    "s vystřelovacím jazykem",
    "s lalokem kolem krku",
    "s plochou hlavou",
    "s kostěnými výrůstky na hlavě",
    "s parohy",
    "s krunýřem",
    "s ochranným exoskeletonem",
    "s bodáky na nohách",
    "s jedovatým bodákem na ocase",
    "s klepety",
    "s chlupatými nohami",
    "s ostny po celém těle",
    "s rohem na nose",
    "s výrůstky pod očima",
    "s blánou pro plachtění",
    "s blánou mezi prsty",
    "s chocholkou na hlavě",
    "s puchýři po těle"
];

VOCAB.BODY = [
    "armor",
    "leather armor",
    "leather jacket",
    "dress",
    "top hat",
    "monk robe",
    "robe",
    "corset",    
    "[MINERAL] armor",
    "cape",    
    "chains",
    "swashbuckler's boots",
    "fur",
    "hood",
    "magic shoes",
    "peasant's rags"  

];

VOCAB.BODY_PART = [
    "[ANIMAL] head",
    "[ANIMAL] eye",
    "[ANIMAL] leg",
];

VOCAB.TOOL_VERB = [
 
];

VOCAB.TOOL = [
    "journal",
    "book",
    "book of [ABSTRACT]",
    "wrench", 
    "keys", 
    "scroll",
    "parasol", 
    "cauldron",
    "herbs",
    "flowers",
    "hunting horn",
    "mirror",
    "flag",
    "banner",
    "beverage",
    "elixir",
    "[ANIMAL|] statuette",
    "saw",
    "enchanted fruit",
    "enchanted [FOOD]"

];

VOCAB.INSTRUMENT_7 = [
    "s flétnou",
    "s kytarou", 
];

VOCAB.WEAPON_7 = [
    "se sekerou",
    "s kladivem",
    "s nožem",
    "s ceremoniálním nožem",
    "s kuší",
    "s mečem",
    "s halapartnou",
    "s tyčí",
    "s žezlem",
    "s hůlkou",
    "s dlouhým mečem",
    "se štítem",
    "s magickými rukavicemi",
    "se dvěma meči",
    "s bičem",    
    "s lukem",
    "s palcátem",
    "s oštěpem",
    "s kouzelnou knížkou",
    "s grimoárem",    
];

// "shaved head",
// "mohawk",
// "war paint",
// "extreme beard",
// "braid",
// "[ANIMAL] companion",
// "scars",
// "medusa hair",
// "horns",
// "fairy wings",
// "feathers",
// "internal power source",
// "piercings",
// "spines",
// "bandages",
// "demonic companion",
// "antlers",
// "thorns",
// "parasitic infection",
// "satyr legs",
// "backpack",
// "medal",