VOCAB.PROFESSION = ["[PROFESSION_M|PROFESSION_F]"];
VOCAB.PROFESSION_M = [
    "čaroděj",
    "lovec", //čeho
    "alchymista",
    "rytíř",
    "rytíř řádu [ADJ:TRAIT:_F_2|] [ELEMENT_F_2]",
    "rytíř řádu [ADJ:TRAIT:_S_2|] [ELEMENT_S_2]",
    "rytíř řádu [ADJ:TRAIT:_M_2|] [ELEMENT_M_2]",
    "rytíř řádu [METAL_ML][_F_2] [ELEMENT_F_2]",
    "rytíř řádu [METAL_ML][_S_2] [ELEMENT_S_2]",
    "rytíř řádu [METAL_ML][_M_2] [ELEMENT_M_2]",
    "kněz",
    "kovář",
    "obchodník", //s čím
    "obchodník s [ANIMAL_7_MN] [ANIMAL_BODY_PART_MN_7]",
    "rebel",
    "lupič",
    "vrah",
    "svůdník",
    "rybář",
    "učitel", //TODO čeho
    "lučištník",
    "strážce",
    "vůdce",
    "hrdina",
    "darebák",
    "trhovec",
    "bard",
    "umělec",
    "putovní bavič",
    "správce klíčů",
    "kníže",
    "kuchař",
    "mnich",
    "ninja",
    "řezník",
    "sluha",
    "kapitán",
    "zabiják", //TODO čeho
];

VOCAB.PROFESSION_2 = [
    "[PROFESSION_M_2|PROFESSION_F_2]"
]

VOCAB.PROFESSION_M_2 = [
    "čaroděje",
    "lovce", //čeho
    "alchymisty",
    "rytíře", // řadu ...
    "kněze",
    "kováře",
    "obchodníka", //s čím
    "rebela",
    "lupiče",
    "vraha",
    "svůdníka",
    "rybáře",
    "učitele", //TODO čeho
    "lučištníka",
    "strážce",
    "vůdce",
    "hrdiny",
    "darebáka",
    "trhovce",
    "barda",
    "umělce",
    "putovního baviče",
    "správce klíčů",
    "knížete",
    "kuchaře",
    "mnicha",
    "ninjy",
    "řezníka",
    "sluhy",
    "kapitána",
    "zabijáka", //TODO čeho
];

VOCAB.PROFESSION_M_7 = [
    "čarodějem",
    "lovcem", 
    "alchymistou",
    "rytířem", 
    "knězem",
    "kovářem",
    "obchodníkem",
    "rebelem",
    "lupičem",
    "vrahem",
    "svůdníkem",
    "rybářem",
    "učitelem",
    "lučištníkem",
    "strážcem",
    "vůdcem",
    "hrdinou",
    "darebákem",
    "trhovcem",
    "bardem",
    "umělcem",
    "putovního bavičem",
    "správcem klíčů",
    "knížetem",
    "kuchařem",
    "mnichem",
    "ninjou",
    "řezníkem",
    "sluhou",
    "kapitánem",
    "zabijákem",
];

VOCAB.PROFESSION_F = [
    "čarodějnice",
    "lovkyně",
    "bojovnice",
    "kněžka",
    "kovářka",
    "obchodnice",
    "rebelka",
    "zlodějka",
    "kurtizána",
    "rybářka",
    "učitelka",
    "lučištnice",
    "strážkyně",
    "vůdkyně",    
    "hrdinka",
    "trhovkyně",
    "akrobatka",
    "umělkyně",
    "kuchařka",
    "pekařka",
    "kapitánka",
    "služka",
    "kněžna",
];

VOCAB.PROFESSION_F_7 = [
    "čarodějnicí",
    "lovkyní",
    "bojovnicí",
    "kněžkou",
    "kovářkou",
    "obchodnicí",
    "rebelkou",
    "zlodějkou",
    "kurtizánou",
    "rybářkou",
    "učitelkou",
    "lučištnicí",
    "strážkyní",
    "vůdkyní",    
    "hrdinkou",
    "trhovkyní",
    "akrobatkou",
    "umělkyní",
    "kuchařkou",
    "pekařkou",
    "kapitánkou",
    "služkou",
    "kněžnou",
];

VOCAB.PROFESSION_F_2 = [
    "čarodějnice",
    "lovkyně",
    "bojovnice",
    "kněžky",
    "kovářky",
    "obchodnice",
    "rebelky",
    "zlodějky",
    "kurtizány",
    "rybářky",
    "učitelky",
    "lučištnice",
    "strážkyně",
    "vůdkyně",    
    "hrdinky",
    "trhovkyně",
    "akrobatky",
    "umělkyně",
    "kuchařky",
    "pekařky",
    "kapitánky",
    "služky",
    "kněžny",
];

VOCAB.PROFESSION_M_4 = [
    "zloděje [ANIMAL_2_MN]",
    "čarodějnice"
]

VOCAB.PROFESSION_MN_4 = [
    "zloděje [ANIMAL_2_MN]",
    "čarodějnice",
    "kurtizány",
    "válečníky",
    "nepřátele státu",
    "umělkyně",
    "služky",
    "sluhy",
    "stráže",
    "obchodníky",
    "řemeslníky",
    "aristokratky",
    "aristokraty",
    "mnichy",
]

VOCAB.PROFESSION_MN_2 = [
    "čarodějů",
    "lovců", //čeho
    "alchymistů",
    "rytířů",    
    "knězů",
    "kovářů",
    "obchodníků", 
    "rebelů",
    "lupičů",
    "vrahů",
    "svůdníků",
    "lékařů",
    "rybářů",
    "učitelů",
    "lučištníků",
    "strážců",    
    "hrdinů",
    "darebáků",
    "trhovců",
    "bardů",
    "umělců",
    "putovních bavičů",
    "správců klíčů",
    "knížat",
    "kuchařů",
    "kultistů",
    "mnichů",
    "ninjů",
    "řezníků",
    "sluhů",
    "kapitánů",
    "zabijáků",
    "čarodějnic",    
    "bojovnic",
    "kněžek",
    "kovářek",
    "obchodnic",
    "rebelek",
    "zlodějek",
    "kurtizán",
    "rybářek",
    "učitelek",
    "lučištnic",        
    "trhovkyň",
    "akrobatek",
    "umělkyň",
    "kuchařek",
    "pekařek",
    "kapitánek",
    "služek",
    "kněžek",
];


VOCAB.PROFESSION_S = [
    //"dítě [PROFESSION_F_2]",
    "nemehlo",
    "trdlo",
    "individuum",
    "monstrum",
    
];

VOCAB.PROFESSION_MN_7 = [
    "čaroději",
    "lovci [ANIMAL_2_MN]", //čeho
    "alchymisty",
    "rytíři",
    "rytíři řádu [ADJ:TRAIT:_F_2] [ELEMENT_F_2]",
    "rytíři řádu [ADJ:TRAIT:_S_2] [ELEMENT_S_2]",
    "rytíři řádu [ADJ:TRAIT:_M_2] [ELEMENT_M_2]",
    "rytíři řádu [METAL_ML][_F_2] [ELEMENT_F_2]",
    "rytíři řádu [METAL_ML][_S_2] [ELEMENT_S_2]",
    "rytíři řádu [METAL_ML][_M_2] [ELEMENT_M_2]",
    "knězi",
    "kováři",
    "obchodníky", 
    "rebely",
    "lupiči",
    "vrahy",
    "svůdníky",
    "rybáři",
    "učiteli",
    "lučištníky",
    "strážci",    
    "hrdiny",
    "darebáky",
    "trhovci",
    "bardy",
    "umělci",
    "putovní baviči",
    "správci klíčů",
    "knížaty",
    "kuchaři",
    "kultisty",
    "mnichy",
    "ninjy",
    "řezníky",
    "sluhy",
    "kapitány",
    "zabijáky",
    "čarodějnicemi",
    "lovkyněmi",
    "bojovnicemi",
    "kněžkami",
    "kovářky",
    "obchodnicemi",
    "rebelkami",
    "zlodějkami",
    "kurtizánami",
    "rybářkami",
    "učitelkami",
    "lučištnicemi",
    "strážkyněmi",    
    "hrdinkami",
    "trhovkyněmi",
    "akrobatkami",
    "umělkyněmi",
    "kuchařkami",
    "pekařkami",
    "kapitánkami",
    "služkami",
    "kněžnami",
];