VOCAB.PROFESSION_M = [
    "čaroděj",
    "lovec", //čeho
    "alchymista",
    "rytíř", // řadu ...
    "kněz",
    "kovář",
    "obchodník", //s čím
    "rebel",
    "lupič",
    "vrah",
    "svůdník",
    "rybář",
    "učitel", //TODO čeho
    "lučištník",
    "strážce",
    "vůdce",
    "hrdina",
    "darebák",
    "trhovec",
    "bard",
    "umělec",
    "putovní bavič",
    "správce klíčů",
    "kníže",
    "kuchař",
    "mnich",
    "ninja",
    "řezník",
    "sluha",
    "kapitán",
    "zabiják", //TODO čeho
];

VOCAB.PROFESSION_F = [
    "čarodějnice",
    "lovkyně",
    "bojovnice",
    "kněžka",
    "kovářka",
    "obchodnice",
    "rebelka",
    "zlodějka",
    "kurtizána",
    "rybářka",
    "učitelka",
    "lučištnice",
    "strážkyně",
    "vůdkyně",    
    "hrdinka",
    "trhovkyně",
    "akrobatka",
    "umělkyně",
    "kuchařka",
    "pekařka",
    "kapitánka",
    "služka",
    "kněžna",
];